### ISSUE TITLE
Add scripts to automatically create basic component file and related files

### ISSUE THREAD

**Issue by madhuni** [NehemiahK/fun-react-lib#14]
We can include some tools like `Plop` to create the basic files for the components. The script will:
- Create a `.jsx` file
- Create a `.css/.scss` file
- Create a `.test.jsx` file

This will basically work more like Angular's `ng generate component`. Which will give the starter files to work with.

**Comment by madhuni** [comment]
If this sounds good. I would like to take this up.

**Comment by NehemiahK** [comment]
Oh this sounds very cool! I'll assign it to you
